README.md

Corrected the repository URL from https://github.com/Podshot/Amulet-Map-Editor to https://github.com/Amulet-Team/Amulet-Map-Editor

Corrected repository URL in README

---

tests/test_format_proto_1.py
tests/test_world.py

This get's rid of a lot of the duplicate code in the world and format_proto_1 tests.

Cleaned up test cases by creating base classes

---

src/api/world_loader.py

I've added some debug messages when matching and identifying worlds.
Additionally, I've filled in a missing error string in the same area.

Added clearer format identification errors

---

src/api/errors.py
src/api/world_loader.py
src/command_line/builtin_commands/world_commands.py
src/command_line/command_api.py
src/utils/format_utils.py
src/version_definitions/java_1_12/java_1_12.py
src/version_definitions/java_1_13/java_1_13.py

I've added the exact map format ranges for 1.12 (1.12 = 1139, 1.12.2 = 1343) and 1.13 (1.13 = 1519, 1.13.1 = 1628). I've also copied over the FML check to the 1.12 file.

Improved version specification

---

src/api/blocks.py

See https://github.com/Amulet-Team/Amulet-Map-Editor/pull/22#issuecomment-428729762

Fixed property names and values in regex used to parse blockstates

---

src/version_definitions/java_1_13/entities/blaze_nbt.json

Added blaze_nbt.json file at path Amulet-Map-Editor/src/version_definitions/java_1_13/entities/

Added blaze_nbt.json

---

src/version_definitions/java_1_13/entities/cave_spider_nbt.json

Added cave_spider_nbt.json file at path Amulet-Map-Editor/src/version_definitions/java_1_13/entities/

Added cave_spider_nbt.json

---

amulet/formats/anvil2/anvil2_world.py

This function was slow and was slowing down chunk loading. The new function is much faster

Faster Chunk Loading

---

README.md

Fix broken link to documentation in README

---

amulet/structure_interface/schematic/schematic.py

Added a few `.value`s where needed

Added missing .value accesses

---

amulet/api/partial_3d_array/bounded_partial_3d_array.py

This fixes an error when pasting with copy air disabled

Added support for setting using a bool array as the item

---

.github/workflows/python-unittests.yml
amulet/api/partial_3d_array/bounded_partial_3d_array.py
amulet/libs/leveldb/leveldb.py
tests/test_db.py
tests/test_speed.py
tests/test_utils.py

Some issues were created from the last pull request. This should fix them
There seems to be some issues with leveldb support on linux.

Fixed tests

---

amulet/world_interface/formats/anvil/anvil_format.py

Java has added vanilla support for custom dimensions. This should allow Amulet to load and modify those

Added support for Java vanilla custom dimensions

---

amulet/api/history/history_manager/database.py
amulet/world_interface/formats/anvil/anvil_format.py

This is a duplicate of #97 but applied to the 1.0 codebase

Fix race condition in v1.0

---

amulet/api/selection/box.py
amulet/api/selection/group.py
tests/test_selection.py

This pull request extends the selection.
It stores the input points as is as well as the minimum and maximum points so that the original points can be used.
It adds methods to add, subtract and merge boxes in a few ways.
It also adds a number of methods that are helpful for various things.

Improve selection

---

amulet/level/formats/anvil_world/format.py
amulet/level/formats/leveldb_world/format.py
amulet/libs/leveldb/__init__.py
amulet/libs/leveldb/leveldb.py

Improved error reporting and handling

Improve error handling

---

amulet/api/chunk/chunk.py
amulet/api/wrapper/chunk/interface.py
amulet/level/formats/construction/format_wrapper.py
amulet/level/formats/mcstructure/format_wrapper.py
amulet/level/formats/schematic/format_wrapper.py
amulet/level/interfaces/chunk/anvil/anvil_1444.py
amulet/level/interfaces/chunk/anvil/anvil_na.py
amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py

Previously only the data that was actively read from the chunk and was stored was written back to the chunk.
This modification will make it so that data that is not handled (new data that we have not written code to handle or custom modded data structures) will be saved into the Chunk object and then written back when saving.

Improved Java and Bedrock interfaces

---

amulet/api/cache.py
amulet/api/chunk/chunk.py

This will speed up startup and shut down times if it is not used

Only create cache database when it is first requested

---

amulet/libs/leveldb/leveldb.py

Added some sanity checking when loading the leveldb library

---

amulet/level/interfaces/chunk/anvil/anvil_na.py

In Java 1.12.2 and before if the block array was deleted but the sub-chunk TAG_Compound remained, the game would recreate that chunk.
This deletes empty sub-chunks so that the game does not error.

Fixed a bug where sub-chunk would get recreated when deleted

---

amulet/api/history/base/history_manager.py
amulet/api/history/history_manager/container.py
amulet/api/history/history_manager/database.py
amulet/api/history/history_manager/meta.py
amulet/api/history/history_manager/object.py
amulet/api/level/base_level/base_level.py

This will allow a loading bar to be displayed

Added an iter method for create undo point

---

amulet/api/chunk/chunk.py
amulet/api/level/immutable_structure/void_format_wrapper.py
amulet/api/selection/box.py
amulet/api/selection/group.py
amulet/api/wrapper/chunk/interface.py
amulet/api/wrapper/format_wrapper.py
amulet/api/wrapper/structure_format_wrapper.py
amulet/api/wrapper/world_format_wrapper.py
amulet/level/formats/anvil_world/format.py
amulet/level/formats/leveldb_world/format.py
amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py

Replaces all `type(obj) is <class>` type checks with `isinstance(obj, <class>)` calls instead, as well as now using `issubclass()` for enforcing the use of subclasses instead of their base classes

Fixed type checking

---

amulet/api/level/base_level/clone.py
amulet/api/partial_3d_array/base_partial_3d_array.py
amulet/api/partial_3d_array/bounded_partial_3d_array.py
amulet/api/partial_3d_array/data_types.py
amulet/api/partial_3d_array/unbounded_partial_3d_array.py
amulet/api/selection/box.py

This dramatically improves the speed of the clone (paste) operation.
In my tests it over 70 times faster than the old code.

Optimise clone

---

amulet/api/level/immutable_structure/void_format_wrapper.py
amulet/api/wrapper/format_wrapper.py
amulet/api/wrapper/structure_format_wrapper.py
amulet/api/wrapper/world_format_wrapper.py
amulet/level/formats/anvil_world/format.py
amulet/level/formats/construction/format_wrapper.py
amulet/level/formats/leveldb_world/format.py
amulet/level/formats/mcstructure/format_wrapper.py
amulet/level/formats/schematic/format_wrapper.py
amulet/level/formats/sponge_schem/format_wrapper.py
tests/test_create_level.py

There was previously an issue with creating worlds.
This should fix that issue and some other related issues

Fixed open and create logic

---

amulet/api/history/history_manager/database.py
amulet/operations/delete_chunk.py

Delete chunks previously took a while because it had to load each chunk

Added a way to side-step the original chunk loading process

---

amulet/level/formats/leveldb_world/format.py

The previous error about marketplace worlds was a bit cryptic. This should make it a bit clearer to users.

Added a warning about marketplace worlds

---

amulet/api/registry/biome_manager.py
amulet/api/registry/block_manager.py
docs_source/api_reference/api/registry/biome_manager.rst
docs_source/api_reference/api/registry/block_manager.rst

This fixes some minor issues in the documentation

Document special members in the registry classes

---

amulet/api/paths.py

I want to ramdisk my cache. this will allow that.

use AMULET_CACHE_DIR as cache dir if possible.

---

amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py

In the latest version I found a case where there was no block storage and the bits_per_block entry was zero.
This should fix loading that.
Note that I think we only save back chunks with a minimum of 4 bits so this will be saved back differently.

Fix for the case where bits_per_block is zero

---

amulet/level/formats/sponge_schem/format_wrapper.py

This should fix Amulet-Team/Amulet-Map-Editor/issues/432

Fixed missing root name in the schem file

---

amulet/api/level/base_level/clone.py

This will create an error log with all the variables to help debug the state when the error happened.

Added code to debug https://github.com/Amulet-Team/Amulet-Map-Editor/issues/339

---

amulet/level/formats/anvil_world/data_pack/data_pack.py

Fixes https://github.com/Amulet-Team/Amulet-Map-Editor/issues/333
Pull the 1.18 pull request before this one
https://github.com/Amulet-Team/Amulet-Core/pull/164

Fixed error loading worlds with missing data pack

---

amulet/level/formats/anvil_world/data_pack/data_pack.py

Fixes https://github.com/Amulet-Team/Amulet-Map-Editor/issues/333
Pull the 1.18 pull request before this one
https://github.com/Amulet-Team/Amulet-Core/pull/164
(Messed up PR #169 and merged to 1.18 branch instead of master, so this is a redo)

Fixed error if data pack does not exist

---

amulet/level/formats/anvil_world/format.py

Fixes https://github.com/Amulet-Team/Amulet-Map-Editor/issues/461

Fixed a KeyError if LastPlayed did not exist

---

amulet/level/formats/leveldb_world/format.py
amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py

Fixes https://github.com/Amulet-Team/Amulet-Map-Editor/issues/565

Fix map editor 565

---

amulet/api/level/base_level/clone.py
requirements/requirements-main.txt

Adds support for block transformation (rotation and mirroring) when pasting a structure.
The actual block rotation is handled in PyMCTranslate in the universal format.

Added block rotation

---

amulet/level/translators/chunk/bedrock/__init__.py

In some cases the same block state can appear multiple times which stack when building the palette making the palette smaller and the indexes pointing to different blocks.
This remaps the blocks if the palette changes size.
Fixes Amulet-Team/Amulet-Map-Editor#654

Fixed block palette stacking bug

---

amulet/level/interfaces/chunk/anvil/anvil_na.py

In Java 1.12 and before if a section exists and the blocks or data within does not, the game will recreate the chunk.
This fixes Amulet-Team/Amulet-Map-Editor#661

Fixed editing Java 1.12 worlds

---

amulet/level/formats/schematic/format_wrapper.py

These fields were being written the wrong way around
Fixes Amulet-Team/Amulet-Map-Editor#400

Fixed schematic AddBlocks

---

amulet/level/interfaces/chunk/anvil/anvil_2844.py
amulet/level/interfaces/chunk/anvil/anvil_na.py

Fixes Amulet-Team/Amulet-Map-Editor#657

Fixed default type for LastUpdate

---

amulet/api/selection/box.py

Fixed degrees and radians bug

---

amulet/level/formats/anvil_world/format.py

Fixes Amulet-Team/Amulet-Map-Editor#757

Fixed milisecond bug

---

amulet/level/formats/leveldb_world/dimension.py

Fixes Amulet-Team/Amulet-Map-Editor#717

Handle some actors not having internalComponents

---

amulet/level/formats/anvil_world/region.py
amulet/utils/world_utils.py

Region files can apparently be uncompressed.
Refactored the code a little.
Solves #149

Add support for region file version 3

---

amulet/level/formats/sponge_schem/format_wrapper.py

Some exporters export empty list tags with type 0
Fixes Amulet-Team/Amulet-Map-Editor#841

Fix parsing empty list tag

---

amulet/level/formats/leveldb_world/format.py

Fixes Amulet-Team/Amulet-Map-Editor#843

Fixed encoding bug for bedrock worlds

---

amulet/api/chunk/biomes.py
tests/test_level/test_biomes.py

Improved biome implementation slightly.
Improved biome tests.
Fixes Amulet-Team/Amulet-Map-Editor#697

Improve biomes

---

amulet/api/block.py

The returned properties value is not mutable

Fixed the typing of block properties

---

amulet/level/formats/leveldb_world/format.py

Fixes Amulet-Team/Amulet-Map-Editor#910

Skip entry if DimensionName is missing

---

amulet/level/formats/anvil_world/format.py

If the tag is not defined then default to 0
Fixes Amulet-Team/Amulet-Map-Editor#932

Added default LastPlayed value
