Amulet-Team/Amulet-Core

- tests/test_box.py
- tests/test_format_proto_1.py
- tests/test_loader.py
- tests/test_world.py
This makes the order consistant across the code and brings it in line
with the error messages, which list the first parameter as expected and
second as actual.
> Fixed order of arguments on assertEquals

- .circleci/config.yml
- requirements-dev.txt
- src/formats/anvil/anvil_world.py
- src/formats/anvil2/anvil2_world.py
- src/utils/world_utils.py
- tests/test_format_proto_1.py
- tests/test_world.py
This makes circleci fail if the code doesn't pass the black stylechecker.
Not sure if this is needed/wanted. Depends on how strictly you want the codestyle to be followed.
Also formats all files that weren't passing.
> Added black stylechecking to circleci

- src/utils/format_utils.py
- src/version_definitions/java_1_12/java_1_12.py
- src/version_definitions/java_1_13/java_1_13.py
I've extracted the logic into common function calls.
The names are obviously up for suggestions but here they are as of writing this:
`check_all_exists` (checks for files/folders)
`check_one_exists` (checks for at least one of a set of files/folders)
`load_leveldat` (Loads the `level.dat` file)
`check_version_leveldat` (Compares the map version to a closed or open range of integers)
My intent with this was to recognize that the format files may grow in quantity going forward and concise requirement specification is critical.
> Improved world loading requirements

- docs_source/api/blocks.rst
- src/api/blocks.py
- tests/test_blocks.py
The Block prototype is complete enough to start being implemented into our main codebase. While this won't be started until this pull request is merged, this is pull request is meant to be a place for discussion on the current prototype and to suggest any changes before the implementation stage. All comments and suggestions are welcome.
* Blockstates are represented by `Block` objects and in addition to the blockstate, a `Block` object can also have a chain of "extra blocks" as extra data to be used in the Minecraft editions that support it.
* This chain of extra blocks is a tuple of other `Block` instances
* `Block` objects are created by calling `Block.get_from_blockstate()` with a blockstate string which is parsed via regex (Credit to @freundTech)
* Blocks can be manipulated by the `+` …
> Merge proto-blocks branch into impl-block-api branch

- .gitignore
- docs_source/api/chunk.rst
- docs_source/api/history_manager.rst
- src/api/chunk.py
- src/api/errors.py
- src/api/history_manager.py
- src/api/world.py
- src/operations/delete_chunk.py
- tests/test_utils.py
- tests/test_world.py
Modified the history manager for Amulet worlds backup the entirety of each chunk's data to disk after every operation completion or after one/multiple changes are made. This is handled internally by the history manager and the chunk's themselves.
- `Chunk` objects now hold their data immediately when created
- In charge of serializing/unserializing themselves from a file via the `pickle` library
- `ChunkHistoryManager` is now a list of dictionaries that maps chunk coordinates to tuples containing the path to the pickled chunk data and the chunk operation performed (IE: delete or edit)
- `undo()`/`redo()` now update the internal `World.chunk_cache` dictionary with the changed chunk data
- Added a "Delete chunks" operation to test how deleting chunks works with undo/redo and added tests to …
> Reworked History Manager to use Chunks instead of Operations

- amulet/api/chunk/blocks.py
- amulet/api/chunk/chunk.py
- amulet/api/chunk/entity_list.py
- amulet/api/chunk/partial_array.py
- amulet/api/structure.py
- amulet/api/world.py
- amulet/operations/clone.py
- amulet/operations/fill.py
- amulet/operations/replace.py
- amulet/world_interface/__init__.py
- amulet/world_interface/chunk/interfaces/anvil/anvil_1444_1_13/anvil_1444_1_13_interface.py
- amulet/world_interface/chunk/interfaces/anvil/anvil_na/interface.py
- amulet/world_interface/chunk/interfaces/anvil/base_anvil_interface.py
- amulet/world_interface/chunk/interfaces/leveldb/base_leveldb_interface.py
- amulet/world_interface/chunk/translators/__init__.py
- amulet/world_interface/formats/__init__.py
- amulet/world_interface/formats/leveldb/leveldb_format.py
- tests/test_convert.py
- tests/test_world.py
Blocks in the chunk class are currently stored as a fixed 16x256x16 array. This has some limitations:
If a mod wants to modify the chunk limit we cannot currently support that.
If a sub-chunk does not exist we currently still need to hold that sub-chunk in memory.
The proposed solution is to turn blocks into something between a sparse and continuous array that allows only required sub-chunks to be in memory.
This solves the above two issues but some experimentation will need to be done to see what performance effects it will have and how much impact it will have on the rest of the code since it is no longer a numpy array. The API has however been modelled on that of a numpy array so hopefully it should be similar enough.
> Added partial array class to handle sub-chunks not existing

- amulet/api/block.py
- amulet/api/chunk/chunk.py
- amulet/api/data_types/wrapper_types.py
- amulet/api/history_manager.py
- amulet/api/structure.py
- amulet/api/world.py
- amulet/api/wrapper/chunk/translator.py
- amulet/api/wrapper/format_wrapper.py
- amulet/api/wrapper/world_format_wrapper.py
- amulet/operations/fill.py
- amulet/operations/paste.py
- amulet/structure_interface/construction/format_wrapper.py
- amulet/structure_interface/construction/interface.py
- amulet/structure_interface/mcstructure/format_wrapper.py
- amulet/structure_interface/mcstructure/mcstructure.py
- amulet/structure_interface/schematic/format_wrapper.py
- amulet/utils/matrix.py
- amulet/world_interface/chunk/interfaces/leveldb/base_leveldb_interface.py
- amulet/world_interface/chunk/translators/bedrock/__init__.py
- amulet/world_interface/chunk/translators/java/java_blockstate/java_blockstate_translator.py
- amulet/world_interface/chunk/translators/java/java_numerical/java_numerical_translator.py
- amulet/world_interface/formats/leveldb/leveldb_format.py
Currently the world palette and chunk classes are distinct things. Without the world palette the block indexes in the Chunk class are meaningless. I suggest we add an attribute to the chunk class that stores the block palette so that the data in the Chunk class has meaning without additional data. All chunks stored in the World class should use the same world block palette so the change is relatively small but this also enables other benefits.
During translation the world palette needs passing into the conversion code as an extra input for for it to add the block states to. I feel it would be better for the conversion code to return a chunk that has a local palette and at the point it is added to the world the data would be remapped to point to the global palette. This would mean the …
> Added a block_palette attribute to the chunk class

- amulet/api/cache.py
- amulet/libs/leveldb/leveldb.py
Before when closing the leveldb it ran the compacting logic which for the cache was pointless because it was getting deleted.
This adds an option to disable that to speed up closing the database.
> Sped up closing the cache

- amulet/api/history/history_manager/database.py
- amulet/level/formats/anvil_world/region.py
There was a race condition with multiple threads trying to load the same region at the same time.
This should make the second thread wait until the first thread has succeeded and then it can proceed.
I have also added a lock into the get_chunk logic so that the same chunk is not loaded twice. This should hopefully fix the case where one chunk is loaded and modified in one thread and then loaded and overwritten by the second thread.
> Fix race condition

- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
- amulet/utils/world_utils.py
Height-maps are stored differently between J1.15 and J1.16.
I don't know why this hasn't caused problems sooner. Perhaps the game handles it.
There were chunks getting reset when converting a world from J1.16 to J1.15. This fixes that.
Added an extra input to encode_long_array that allows specifying the number of bits per value.
Decoded and encoded the height arrays using the long array logic so that it can be converted between the two formats.
> Fixed Java heightmaps

- amulet/level/formats/anvil_world/region.py
Previously locks were added to the Java region code to fix some chunk loading issues with threads.
This extends that to encase all code that modifies the state of _chunks in locks.
There was a case where the region file was being loaded and then unloaded in another thread before the first had a chance to access the data leading to a None type is not iterable error.
> Added more locks to Java region

- amulet/api/history/history_manager/container.py
- amulet/api/history/history_manager/meta.py
- amulet/api/level/base_level/base_level.py
This allows the creation of an undo point for either world, non-world, both and technically neither.
This is more clear and more powerful
> Disconnected world and non-world history managers

- amulet/api/selection/box.py
- amulet/api/selection/group.py
- tests/test_box.py
This pull request reworks the selection logic to make it immutable. This seems more logical because before there were only methods to add boxes and none to remove them. It will also make other things a bit easier.
The SelectionGroup class holds the boxes as they are given to it and does not manipulate them. It has a method that will merge the selections if desired. This gives operations more control over what they are given rather than an unpredictable input.
It also fixes a number of issues that were previously present.
Future work will be needed in the merging method to produce a better result and remove duplicate areas.
> Rework selection

- amulet/api/history/history_manager/database.py
- amulet/api/level/base_level/chunk_manager.py
I received an error from the temporary database changing size which can only happen if two threads are interacting with the code.
This should lock the code so that only one thread can access it at once.
> Improved thread safety of the chunk database

- amulet/api/chunk/chunk.py
- amulet/api/history/base/history_manager.py
- amulet/api/history/history_manager/container.py
- amulet/api/history/history_manager/database.py
- amulet/api/history/history_manager/meta.py
- amulet/api/history/history_manager/object.py
- amulet/api/level/base_level/base_level.py
- amulet/api/level/base_level/chunk_manager.py
This adds a method to unload all cached data so that it can be repopulated from the original world database.
The reason for adding this is to enable switching between programs that manipulate the high level universal representation in the Level classes and those that manipulate the low level data as it appears in the world database.
Without this if the higher level data is saved it will overwrite any low level modifications that were made.
It also cleans up the pickle methods in the Chunk class. They now take and return the pickled bytes rather than saving them directly to the leveldb cache.
> Added method to unload cached data. Cleaned up pickle.

- amulet/api/selection/group.py
- tests/test_world.py
The `SelectionGroup` class is a container of zero or more `SelectionBox` classes. It makes more sense for the `__iter__` method to be an iterable of the `SelectionBox` classes than of the blocks.
Added a `blocks` method to replace the old __iter__ method.
Fixed a bug with `__contains__`
> Fixed some issues in the selection group

- amulet/api/chunk/entity_list.py
- amulet/api/errors.py
- amulet/api/history/history_manager/container.py
- amulet/api/history/history_manager/database.py
- amulet/api/history/revision_manager/disk.py
- amulet/api/level/base_level/base_level.py
- amulet/api/level/base_level/chunk_manager.py
- amulet/api/level/immutable_structure/void_format_wrapper.py
- amulet/api/player/player_manager.py
- amulet/api/selection/box.py
- amulet/api/wrapper/format_wrapper.py
- amulet/api/wrapper/structure_format_wrapper.py
- amulet/api/wrapper/world_format_wrapper.py
- amulet/level/formats/anvil_world/dimension.py
- amulet/level/formats/anvil_world/format.py
- amulet/level/formats/construction/format_wrapper.py
- amulet/level/formats/leveldb_world/format.py
- amulet/level/formats/mcstructure/format_wrapper.py
- amulet/level/formats/schematic/format_wrapper.py
- amulet/level/formats/sponge_schem/format_wrapper.py
- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
- amulet/libs/leveldb/leveldb.py
- tests/test_db.py
- tests/test_world.py
Cleaned up the database class so that lots of the logic does not need duplicating for the player class and other future classes.
Added lower level get methods so the data can be accessed in this form not just in the player class. At some point the `Player` class will go through the translator to convert the inventory.
Added custom errors for the player.
Cleaned up and added some things to the leveldb class.
> Cleaned up the database logic

- amulet/level/formats/anvil_world/format.py
These lighting changes for Java were causing more issues than they solved.
With the changes all light emitting blocks break until updated.
Without the changes the light remained as it did before but deleting and adding things causes lighting issues. This seems like the better of the two options.
> Reverted lighting changes

- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
1.13 worlds must have the BlockStates and Palette keys defined if the section exists.
If they do not the chunk will get reset.
This deletes the sections that do not have those keys defined
This should fix Amulet-Team/Amulet-Map-Editor/issues/326
> Removed empty sections if saving to a 1.13 world

- amulet/operations/fill.py
The previously used method loaded all of the chunks.
This means the loading bar would stay at 0 for a little bit.
The replaced method should be quicker and the chunk loading done while the loading bar is updated.
> Switched out get_chunk_slice_box for get_coord_box

- amulet/level/formats/mcstructure/format_wrapper.py
This should fix Amulet-Team/Amulet-Map-Editor/issues/356
Structure void blocks are a special case in the mcstructure file.
Instead of being saved as the actual blockstate it is saved out as -1 in the block array.
This effectively means there is no block there.
In the loading logic I convert -1 to a structure void block since we don't have the concept of no block and the reverse on saving.
Perhaps in the future we can add an option to the paste UI to not paste structure void blocks. I would however like to make that more general.
> Fixed structure_void blocks in mcstructure files

- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
If the height of the world has been changed a different heightmap size could be expected.
If this is the case the game just discards the old height and creates it again so we will discard it too.
This should fix Amulet-Team/Amulet-Map-Editor/issues/344
> Allow heightmap errors

- amulet/api/abstract_base_entity.py
- amulet/api/block.py
- amulet/api/block_entity.py
- amulet/api/chunk/block_entity_dict.py
- amulet/api/chunk/chunk.py
- amulet/api/level/base_level/base_level.py
- amulet/api/level/immutable_structure/void_format_wrapper.py
- amulet/api/wrapper/chunk/interface.py
- amulet/api/wrapper/chunk/translator.py
- amulet/level/formats/construction/data_types.py
- amulet/level/formats/construction/format_wrapper.py
- amulet/level/formats/construction/interface.py
- amulet/level/formats/construction/section.py
- amulet/level/formats/leveldb_world/format.py
- amulet/level/formats/mcstructure/format_wrapper.py
- amulet/level/formats/mcstructure/interface.py
- amulet/level/formats/schematic/interface.py
- amulet/level/formats/sponge_schem/interface.py
- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
- amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py
- amulet/level/interfaces/chunk/leveldb/leveldb_chunk_versions.py
- amulet/level/translators/chunk/bedrock/__init__.py
- amulet/level/translators/chunk/java/java_blockstate_translator.py
- amulet/level/translators/chunk/java/java_numerical_translator.py
There were a lot of cases where Tuple[int, int, int] was typed out in full for both block location and version numbers.
This should change them to refer to the centralised version in the data_types package.
> Changed hard coded typing to refer to the data_types package

- amulet/level/interfaces/chunk/anvil/anvil_1444.py
The rewritten long array parsing logic returns the array in the smallest data type it will fit in.
This caused issues when adding the offset. Instead of converting to the next data type it instead overflowed giving random blocks.
This casts the unpacked array to a uint32 array.
This should fix Amulet-Team/Amulet-Map-Editor/issues/365
> Fixed an issue loading Java chunks

- amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py
Older versions of Bedrock edition stored the generation state as a byte rather than an int.
This handles both cases.
Fixed https://github.com/Amulet-Team/Amulet-Map-Editor/issues/464
Pull the 1.18 pull request before this one
https://github.com/Amulet-Team/Amulet-Core/pull/164
> Fix Amulet-Map-Editor/464

- amulet/level/formats/anvil_world/format.py
- amulet/level/formats/leveldb_world/format.py
Fixed https://github.com/Amulet-Team/Amulet-Map-Editor/issues/448
This forces player position and rotation to be in the range +/-100M
If the player rotation is NaN this causes other issues.
Also handles the case that position or rotation is not defined.
This issue was only noticed in Java but making the changes to Bedrock just in case.
> Fixed player rotation being NaN

- amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py
Bedrock biome arrays were getting their x and y axis swapped when saving.
This fixes that.
This may be the issue from https://github.com/Amulet-Team/Amulet-Map-Editor/issues/507 and https://github.com/Amulet-Team/Amulet-Map-Editor/issues/523
> Fixed an array rotation bug when saving Bedrock biomes

- amulet/level/formats/sponge_schem/varint/VARINT_LICENSE
- amulet/libs/leveldb/LICENSE-LEVELDB
In British English the noun is spelt "licence" and "license" as a verb.
Changing this to match American English.
> Fixed license spelling

- amulet/__init__.py
- amulet/api/chunk/chunk.py
- amulet/api/level/base_level/base_level.py
- amulet/api/wrapper/chunk/interface.py
- amulet/api/wrapper/format_wrapper.py
- amulet/level/formats/anvil_world/dimension.py
- amulet/level/formats/anvil_world/format.py
- amulet/level/interfaces/chunk/anvil/anvil_0.py
- amulet/level/interfaces/chunk/anvil/anvil_1444.py
- amulet/level/interfaces/chunk/anvil/anvil_1466.py
- amulet/level/interfaces/chunk/anvil/anvil_1467.py
- amulet/level/interfaces/chunk/anvil/anvil_1484.py
- amulet/level/interfaces/chunk/anvil/anvil_1503.py
- amulet/level/interfaces/chunk/anvil/anvil_1519.py
- amulet/level/interfaces/chunk/anvil/anvil_1631.py
- amulet/level/interfaces/chunk/anvil/anvil_1908.py
- amulet/level/interfaces/chunk/anvil/anvil_1912.py
- amulet/level/interfaces/chunk/anvil/anvil_1934.py
- amulet/level/interfaces/chunk/anvil/anvil_2203.py
- amulet/level/interfaces/chunk/anvil/anvil_2529.py
- amulet/level/interfaces/chunk/anvil/anvil_2681.py
- amulet/level/interfaces/chunk/anvil/anvil_2709.py
- amulet/level/interfaces/chunk/anvil/anvil_2844.py
- amulet/level/interfaces/chunk/anvil/anvil_na.py
- amulet/level/interfaces/chunk/anvil/base_anvil_interface.py
- amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py
Interfaces are the classes that bridge the gap between the raw chunk format and our internal chunk structure.
They extract the required data from the raw chunk data and populate our chunk class with the data. They also do the reverse when saving.
There is then a secondary translation state which converts to our universal format and back again.
Previously the individual interface features (blocks, entities, biomes, ...) were all closely linked which made updating for new features and removing old features rather difficult.
The new implementation fully splits up each feature so that no feature depends on the behaviour of another feature or any pre-processing steps. This means that we can more easily disable features and update them.
This pull request also introduces temporary features to …
> Refactored Java interfaces and added temporary entity support

- amulet/level/formats/leveldb_world/dimension.py
- amulet/level/formats/leveldb_world/format.py
The leveldb object has been moved into the format class so that it can be accessed easier.
A public property has been added for direct accessing.
Cleaned up some first party calls to the old private storage.
> Moved the leveldb object out of the dimension class

- amulet/libs/leveldb/leveldb.py
There are some cases where opening a leveldb database throws an error.
To fix this we should try and repair the database before opening.
Fixes Amulet-Team/Amulet-Map-Editor#319
Fixes Amulet-Team/Amulet-Map-Editor#653
> Repair leveldb databases before opening them

- amulet/api/level/base_level/base_level.py
This solves issues of chunks being copied if they are mid-generation to different platforms and becoming void chunks.
Fixes Amulet-Team/Amulet-Map-Editor#528
> Only copy chunks to the new world if they are full chunks

- amulet/level/formats/leveldb_world/interface/chunk/base_leveldb_interface.py
In some cases the block palette length can be 0.
The game does not like these chunks and throws a lot of errors but is able to load them.
It defaults to an air block palette which I have used here.
Fixes Amulet-Team/Amulet-Map-Editor#555
> Fixed loading Bedrock chunks with no palette

- amulet/level/interfaces/chunk/anvil/anvil_1444.py
If a block property is not a string then discard it when saving
Might fix Amulet-Team/Amulet-Map-Editor#513
> Force Java properties to be strings

- amulet/level/interfaces/chunk/anvil/anvil_2844.py
The chunk format did not change over the 1.19 release so the old interface should work just fine.
> Bumped the Java interface version to support 1.19

- amulet/api/level/immutable_structure/void_format_wrapper.py
- amulet/api/wrapper/__init__.py
- amulet/api/wrapper/format_wrapper.py
- amulet/api/wrapper/structure_format_wrapper.py
- amulet/api/wrapper/world_format_wrapper.py
- amulet/level/formats/anvil_world/format.py
- amulet/level/formats/construction/format_wrapper.py
- amulet/level/formats/leveldb_world/format.py
- amulet/level/formats/mcstructure/format_wrapper.py
- amulet/level/formats/schematic/format_wrapper.py
- amulet/level/formats/sponge_schem/format_wrapper.py
With the previous implementation it was ambiguous which form of version each class used.
With generics, subclasses can define the version type and define the type in the base class methods without redefining them.
This also cleans up a bit of other version code as well
> Switched version typing to use a generic

- amulet/level/formats/leveldb_world/format.py
- amulet/libs/leveldb/__init__.py
- amulet/libs/leveldb/leveldb.py
The previous code was running the repair logic each time the world was loaded.
This was creating a lost directory with an increasing amount of data.
The new implementation only runs the repair logic if the world did not open correctly.
If opening raised an OSError (usually marketplace worlds) a new distinct error is raised.
Repair could partially fix the marketplace leveldb but not fully causing chunks to get deleted.
This reverts it so that marketplace worlds always throw an error when loading.
Fixes Amulet-Team/Amulet-Map-Editor#721
> Fixed some issues with leveldb worlds

- tests/data/util.py
- tests/test_format_wrapper/test_create_level.py
- tests/test_format_wrapper/test_encode_decode.py
- tests/test_format_wrapper/test_height.py
- tests/test_format_wrapper/test_loader.py
- tests/test_format_wrapper/test_speed.py
- tests/test_level/test_player.py
- tests/test_level/test_world.py
- tests/test_util/test_long_array.py
Tests were importing modules from the tests directory relative to the repository root.
This cause conflicts if multiple repositories are added to the path.
The correct way to run tests is to run the tests directory as the current working directory and import as if tests was the root.
> Fixed importing in tests

- amulet/level/interfaces/chunk/anvil/anvil_1519.py
- amulet/level/interfaces/chunk/anvil/anvil_1901.py
- amulet/level/interfaces/chunk/anvil/anvil_1908.py
Defined sections in Java 1.13.2 must have Palette and Blockstates defined otherwise the chunk will get rejected.
Fixes Amulet-Team/Amulet-Map-Editor#758
> Fix chunk reject bug in Java 1.13.2

- amulet/level/interfaces/chunk/anvil/anvil_2844.py
- amulet/utils/world_utils.py
- tests/test_util/test_long_array.py
Fixed an exception with biome palettes of length 1
`(0).bit_length() == 0` but for our case it needs to be stored in at least 1 bit.
Fixes Amulet-Team/Amulet-Map-Editor#751
> Fixed biome bug

- amulet/level/formats/leveldb_world/interface/chunk/base_leveldb_interface.py
I found a chunk in a world that did not have the "states" or "val" field.
In this case we should assume that it is the states format but there are no properties for the block.
The example I found was an air block.
> Fix Bedrock chunk loading bug

- amulet/api/cache.py
- amulet/api/level/base_level/base_level.py
- amulet/api/level/base_level/chunk_manager.py
- amulet/api/paths.py
The global cache was problematic if multiple processes were spawned because they would all try and open the same cache directory.
This eemoves the global cache location and adds a cache per level.
The cache is now stored in the system temp directory as found using the tempfile module.
A custom class has been added to handle automatic deletion of the cache directory when the instance is lost.
Worst case if the program crashes they will be deleted after a week if the lock file is still not being used.
Fixes Amulet-Team/Amulet-Map-Editor#614 and #154
> Replaced global cache db with a per level db

- amulet/api/block.py
This classmethod behaves like the reverse of the iter method.
This behaviour is possible with the default constructor but requires a bit of extra work.
This should streamline a bit of code that needs to do this.
> Added Block.join classmethod

- amulet/level/formats/anvil_world/_sector_manager.py
> Import missing `bisect_left` function for Python version >= 3.10

- amulet/api/abstract_base_entity.py
- amulet/level/formats/leveldb_world/interface/chunk/base_leveldb_interface.py
- amulet/level/formats/mcstructure/interface.py
If the namespace is omitted in the block name it will default to "minecraft"
This fixes an issue reported on discord
> Added default namespace support for Bedrock

- amulet/__pyinstaller/hook-amulet.py
Include all modules as hidden imports to make sure they all get included. The depreciated leveldb import path was not being included because it is no longer used by first party code.
> Fixed hidden import error

- amulet/api/cache.py
- amulet/level/formats/anvil_world/format.py
If a path contained any of the special glob characters it would throw an error when searching with glob. This escapes the path before giving to glob.
Fixes Amulet-Team/Amulet-Map-Editor#839
> Escape path before giving to glob

- amulet/level/formats/schematic/format_wrapper.py
- amulet/level/formats/sponge_schem/format_wrapper.py
Occasionally sponge schematics have the extension .schematic instead of the normal .schem. This code tries opening the file and validating the contents.
Resolves Amulet-Team/Amulet-Map-Editor#872
> Fixed importing sponge schematics with wrong extension

- amulet/level/formats/leveldb_world/interface/chunk/leveldb_chunk_versions.py
The tuple comparison is false for the case `(1, 0, 0) <= (1, 0)` which causes problems for version numbers with implied zeros. To fix this I have padded the version to 4 numbers. I have also returned the number 6 chunk version if all else fails.
Fixes Amulet-Team/Amulet-Map-Editor#835
> Fixed issues getting Bedrock chunk version

- amulet/level/interfaces/chunk/anvil/anvil_2844.py
When the chunk was restructured to move the data into the root some tags were missed.
This adds a few missed tags. Most notably `xPos` and `zPos`.
Remove the old `Level` tag after the chunk has been encoded.
Fixes Amulet-Team/Amulet-Map-Editor#583
Fixes Amulet-Team/Amulet-Core#235
> Fixed two issues with Java chunks

- amulet/level/translators/chunk/bedrock/__init__.py
This does not have any effect in most cases but if the block is a modded block it would previously get left in. Refactored the code a little as well.
> Remove __version__ before converting

- amulet/api/wrapper/format_wrapper.py
- amulet/level/formats/anvil_forge_world.py
- amulet/level/formats/anvil_world/format.py
This code changes now traverses the `dimensions` directory tree and searches for the following directories to exist to determine if the parent directory is a dimension: `data`, `entities`, `poi` and `region`
Notes:
- This logic can also be migrated to `anvil_world/format.py` [here](https://github.com/Amulet-Team/Amulet-Core/blob/main/amulet/level/formats/anvil_world/format.py#L415) but I put it into the `anvil_forge_world.py` file for now since it's Forge specific. Feel free to let me know if you want me to migrate it
Resolves Amulet-Team/Amulet-Map-Editor#922
> Added logic to traverse the dimensions directory tree
